version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: fastapi_postgres
    env_file:
      - backend/app/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    container_name: fastapi_redis
    ports:
      - "6379:6379"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    env_file:
      - backend/app/.env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_celery
    command: poetry run celery -A backend.app.api.deps.celery_app worker --loglevel=info --pool=solo
    env_file:
      - backend/app/.env
    depends_on:
      fastapi:
        condition: service_started

volumes:
  postgres_data: